name: Docs Build (dpp.dev)
on:
  push:
    branches:
      - 'dev'
    files:
      - '**Doxyfile'
      - '**docpages/**'
      - '**/*.h'
      - '**/documentation.yml'

permissions:
  contents: read

jobs:
  docs:
    permissions:
      contents: write # Needs to be able to write to the repo.
    name: Build Documentation
    runs-on: ubuntu-20.04

    concurrency: 
      group: docs-deployment
      cancel-in-progress: true

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: Setup PHP
        uses: shivammathur/setup-php@c665c7a15b5295c2488ac8a87af9cb806cd72198 # v2
        with:
          php-version: '8.0'

      - name: Checkout D++
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          submodules: recursive

      - name: Generate Docs
        run: cd docpages && php makedocs-gh.php
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

